name: Build Test Package

on:
  push:
    branches: [ master ]
    paths-ignore: ['**.md']

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Install dependencies
      run: dotnet restore ./source/Lexicala.NET.slnx
    - name: Build
      run: dotnet build ./source/Lexicala.NET.slnx --configuration Release --no-restore
    - name: Test
      run: dotnet test ./source/Lexicala.NET.slnx --no-restore --verbosity normal
    - name: Publish to Nuget
      uses: alirezanet/publish-nuget@v3.0.4
      with: 
          PROJECT_FILE_PATH: ./source/Lexicala.NET/Lexicala.NET.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
