name: Build and Push to Nuget - Autofac

on:
  push:
    branches: [ master ]
    paths-ignore: '**.md'

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore ./source/Lexicala.NET.sln
    - name: Build
      run: dotnet build ./source/Lexicala.NET.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./source/Lexicala.NET.sln --no-restore --verbosity normal
    - name: Publish to Nuget
      uses: alirezanet/publish-nuget@v3.0.4
      with: 
          PROJECT_FILE_PATH: ./source/Lexicala.NET.Autofac/Lexicala.NET.Autofac.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
